language: node_js
sudo: false
node_js:
  - lts/*
cache:
  directories:
    # - contract/tests/node_modules
services:
  - docker
jobs:
  include:
    - stage: Start CITA
      before_install:
        - cd contract/tests
      install:
        - yarn install
      before_script:
        - mkdir cita
        - wget https://github.com/cryptape/cita/releases/download/v0.16/cita_secp256k1_sha3.tar.gz -O $PWD/cita/cita-v0.16.tar.gz
        - tar -xvf $PWD/cita/cita-v0.16.tar.gz -C $PWD/cita
        - docker pull cita/cita-build:ubuntu-18.04-20180703-solc-0.4.19
        - cd $PWD/cita/cita-v0.16
        - ./env.sh scripts/create_cita_config.py --create --nodes '127.0.0.1:4000'
        - ./env.sh bin/cita setup nodes/0
        - ./daemon.sh bin/cita start nodes/0
      script:
        - npm test
